name: Test and Build

on:
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [16.x]
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            # - name: npm 7
            #   run: npm i -g npm@7

            - name: npm install, test and build
              run: |
                  npm ci
                  npm run lerna-publish-install
                  npm run echo-test
                  npm run lerna-build
              env:
                  CI: TRUE
