name: Build and Publish

on:
    release:
        types:
            - published
jobs:
    release-pkg:
        name: Create release
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  token: ${{ secrets.git_token }}
                  fetch-depth: 0

            - name: Setup node
              uses: actions/setup-node@v2
              with:
                  registry-url: https://registry.npmjs.org

            - name: Config git user
              run: |
                  git config --global user.name "${{ github.actor }}"
                  git config --global user.email "${{ github.actor }}@users.noreply.github.com"
                  git fetch --depth=1 origin +refs/tags/*:refs/tags/*

            - name: npm 7
              run: npm i -g npm@7

            - name: npm install and build
              run: |
                  npm ci
                  npm run lerna-publish-install
                  npm run lerna-build
              env:
                  CI: TRUE

            - name: Bump versions
              run: |
                  git checkout main
                  npx lerna version --yes --conventional-commits --create-release github
              env:
                  GH_TOKEN: ${{ github.token }}

            - name: Release packages
              run: npx lerna publish from-git
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.npm_token }}
